# Generated by Django 2.2.21 on 2022-11-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_userinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
